igniterealtime/Spark

src/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java
https://igniterealtime.org/issues/browse/SPARK-1604
=> Fix two settings overlapping in the Preferences

src/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
(patch by Aleksey)
https://igniterealtime.org/issues/browse/SPARK-1512
=> Fix for ***<user> is online at message does not always show in chat room

src/java/org/jivesoftware/spark/util/StringUtils.java
history (patch by Jason Sipula)
https://igniterealtime.org/issues/browse/SPARK-1513
=> Fix - After receiving XML data as a message Spark stops displaying

src/java/org/jivesoftware/spark/ui/ContactItem.java, src/java/org/jivesoftware/spark/ui/themes/ThemePanel.java, src/java/org/jivesoftware/spark/ui/themes/ThemePreference.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties, src/resources/i18n/spark_i18n_de.properties, src/resources/i18n/spark_i18n_lt.properties
(original patch by Niklas, updated to current source)
https://igniterealtime.org/issues/browse/SPARK-979
=> Add option to disable dimming of idle users (default is to dim)

src/plugins/spelling/src/java/org/jivesoftware/spellchecker/SpellcheckerPreference.java, src/plugins/spelling/src/java/org/jivesoftware/spellchecker/SpellcheckerPreferences.java
https://igniterealtime.org/issues/browse/SPARK-1617
=> Fix loading of Spellchecker's IgnoreUppercase setting

src/java/org/jivesoftware/LoginSettingDialog.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties, src/resources/i18n/spark_i18n_lt.properties
https://igniterealtime.org/issues/browse/SPARK-1619
=> Use version as resource option

src/java/org/jivesoftware/LoginDialog.java
https://igniterealtime.org/issues/browse/SPARK-1619
=> Use version as resource option (additional change)

src/plugins/roar/src/resources/i18n/roar_i18n.properties, src/plugins/roar/src/resources/i18n/roar_i18n_lt.properties
https://igniterealtime.org/issues/browse/SPARK-1621
=> Add "0 = infinite" caption to roar duration option

src/plugins/roar/src/resources/i18n/roar_i18n_de.properties, src/plugins/roar/src/resources/i18n/roar_i18n_fr.properties, src/plugins/roar/src/resources/i18n/roar_i18n_pl.properties
https://igniterealtime.org/issues/browse/SPARK-1621
=> Additional changes to other translations (roar duration)

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/LoginSettingDialog.java, src/java/org/jivesoftware/resource/Default.java, src/java/org/jivesoftware/resource/default.properties
https://igniterealtime.org/issues/browse/SPARK-1622
=> Add options to default.properties to use hostname or version as resource

src/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java
https://igniterealtime.org/issues/browse/SPARK-1614
=> Add an option to show seconds in a message time stamp

src/java/org/jivesoftware/spark/ui/status/StatusBar.java
https://igniterealtime.org/issues/browse/SPARK-1458
=> Do not prepend default status text to the custom status

src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
https://igniterealtime.org/issues/browse/SPARK-1627
=> Change default reconnect display to Display in contact group

src/java/org/jivesoftware/spark/ui/TranscriptWindow.java
https://igniterealtime.org/issues/browse/SPARK-905
=> Add date stamp for current messages in the chat window

src/java/org/jivesoftware/spark/ui/TranscriptWindow.java
https://igniterealtime.org/issues/browse/SPARK-1631
=> Fix chat messages not being shown when there are no old history showing

src/java/org/jivesoftware/sparkimpl/profile/AvatarPanel.java, src/resources/i18n/spark_i18n.properties, src/resources/i18n/spark_i18n_lt.properties
https://igniterealtime.org/issues/browse/SPARK-1472
=> Add translation for avatar label

src/java/org/jivesoftware/spark/ui/ContactList.java, src/java/org/jivesoftware/spark/ui/themes/ThemePanel.java, src/java/org/jivesoftware/sparkimpl/plugin/gateways/GatewayButton.java, src/java/org/jivesoftware/sparkimpl/plugin/gateways/GatewayTabItem.java, src/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java, src/plugins/otr/src/java/org/jivesoftware/spark/otrplug/impl/OTRSession.java, src/plugins/sip/src/java/org/jivesoftware/sparkplugin/ui/call/CallManager.java
https://igniterealtime.org/issues/browse/SPARK-1329
=> Additional translations for buttons

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
https://igniterealtime.org/issues/browse/SPARK-1473
=> Adding nickname to Alert toast

src/java/org/jivesoftware/spark/ui/ContactInfoWindow.java
https://igniterealtime.org/issues/browse/SPARK-1571
=> Add phone number to vcard popup

build/build.xml, build/installer/spark-izpack5.xml
I've added "installer.izpack5" to the build/build.xml file.
I've also created an XML file for the new IzPack 5 syntax.
=> IzPack 5 Support

src/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java
https://igniterealtime.org/issues/browse/SPARK-1517
=> Append contact name on every line of conversation history

build/build.xml
https://igniterealtime.org/issues/browse/SPARK-1144
=> Ant buildscript should not check for explicit Ant version numbers

src/java/org/jivesoftware/resource/Default.java, src/java/org/jivesoftware/resource/default.properties, src/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java, src/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscriptPlugin.java, src/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java, src/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java
https://igniterealtime.org/issues/browse/SPARK-1436
=> Option to force disabling history

src/java/org/jivesoftware/resource/Default.java, src/java/org/jivesoftware/resource/default.properties, src/java/org/jivesoftware/spark/ui/TranscriptWindow.java, src/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java
https://igniterealtime.org/issues/browse/SPARK-1638
=> Add option to hide chat history settings via default.properties

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/resource/Default.java, src/java/org/jivesoftware/resource/default.properties, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferencePanel.java
https://igniterealtime.org/issues/browse/SPARK-1640
=> Option to hide Save Password

src/java/org/jivesoftware/spark/ui/ChatContainer.java
https://igniterealtime.org/issues/browse/SPARK-1642
=> Update the Bring window to front code

src/java/org/jivesoftware/spark/ui/ContactList.java
https://igniterealtime.org/issues/browse/SPARK-1592
=> Should not show 'Send a file' menu when file transfer is disabled

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/resource/Default.java, src/java/org/jivesoftware/resource/default.properties, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferencePanel.java
box
https://igniterealtime.org/issues/browse/SPARK-1644
=> Add an option to hide auto login checkbox along with the save password

src/java/org/jivesoftware/spark/ui/ContactGroup.java, src/java/org/jivesoftware/spark/ui/ContactItem.java
https://igniterealtime.org/issues/browse/SPARK-847
=> Make offline group use global font size instead of hardcoded

src/java/org/jivesoftware/spark/ui/ChatContainer.java
https://igniterealtime.org/issues/browse/SPARK-1648
=> Should now show toast popups for new messages in MUC

src/plugins/transferguard/src/java/org/jivesoftware/spark/plugins/transfersettings/TransferSettingsPreference.java, src/plugins/transferguard/src/resources/i18n/transferguard_i18n.properties, src/plugins/transferguard/src/resources/i18n/transferguard_i18n_lt.properties
https://igniterealtime.org/issues/browse/SPARK-1651
=> Add i18n translation string for Transfer Guard title

src/plugins/transferguard/src/resources/i18n/transferguard_i18n_zh_TW.properties
https://igniterealtime.org/issues/browse/SPARK-1653
=> Add Chinese traditional translation for Transfer Guard plugin

src/java/org/jivesoftware/LoginDialog.java
https://igniterealtime.org/issues/browse/SPARK-1066
=> Applying old proxy patch

src/java/org/jivesoftware/spark/Workspace.java, src/java/org/jivesoftware/spark/ui/TranscriptWindow.java, src/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java, src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java, src/java/org/jivesoftware/sparkimpl/preference/sounds/SoundPlugin.java, src/plugins/fastpath/src/java/org/jivesoftware/fastpath/workspace/panes/ChatViewer.java
=> Replace deprecated XEP-0091 with XEP-0203.

src/plugins/fastpath/src/resources/i18n/fastpath_i18n_lt.properties, src/plugins/spelling/src/resources/i18n/spellchecker_i18n_lt.properties
https://igniterealtime.org/issues/browse/SPARK-1675
=> Add Lithuanian Fastpath translation

src/java/org/jivesoftware/sparkimpl/plugin/bookmarks/BookmarkPlugin.java
https://igniterealtime.org/issues/browse/SPARK-1667
=> Make Bookmarks menu always be at 4 place

src/java/org/jivesoftware/sparkimpl/plugin/bookmarks/BookmarkPlugin.java
https://igniterealtime.org/issues/browse/SPARK-1667
=> Don't show empty Bookmarks menu

src/java/org/jivesoftware/sparkimpl/plugin/phone/PhonePlugin.java
SPARK-1684
Increased timeout for pop up from 5 sec to 15 sec.
=> Spark 1684 Toaster Pop up for Incoming Call Timeout

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
added increment for Broadcast Plugin https://igniterealtime.org/issues/browse/SPARK-1530
=> Added Increase message count Spark-1530

src/java/org/jivesoftware/Spark.java, src/java/org/jivesoftware/spark/PluginManager.java, src/java/org/jivesoftware/sparkimpl/plugin/emoticons/EmoticonManager.java
This should resolve the plugin/sound/emoticon issues with the mac build to closer mimic the same behavior as the other platforms.  I tested this on windows and max os x, but did not test it with linux.
=> Spark-1701, Spark-1696, Spark-1620

build/build.xml, src/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java, src/java/org/jivesoftware/sparkimpl/plugin/phone/PhonePlugin.java
Updated path for jre per https://community.igniterealtime.org/thread/58247
=> SPARK-1674

src/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java, src/java/org/jivesoftware/sparkimpl/plugin/phone/PhonePlugin.java
Spark is getting stuck with "On Phone" status after unlocking Windows. I found a few issues with my last PR in regards to my previous attempts to resolve.
UserIdlePlugin and PhonePlugin both change presences, and sometimes there are conflicts.  This is an attempt to address those conflicts. This is likely the the worlds least efficient code, and the long way of doing things.
=> SPARK-1455

src/java/org/jivesoftware/sparkimpl/plugin/scratchpad/PrivateNotes.java
Fix for Spark-1714 (https://igniterealtime.org/issues/browse/SPARK-1714)
=> Fix for Spark-1714

src/java/org/jivesoftware/sparkimpl/plugin/phone/PhonePlugin.java, src/java/org/jivesoftware/sparkimpl/preference/notifications/NotificationsPreference.java, src/java/org/jivesoftware/sparkimpl/preference/notifications/NotificationsUI.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties
Added option to disable incoming call notification popup when using asterisk-im plugin.
=> SPARK-1720 Add option to disable Incoming Call notification popup

build/installer/spark.install4j
Exclude linux x64 native libraries from windows builds
=> Exclude linux x64 native libraries from windows builds

src/java/org/jivesoftware/spark/ui/ChatArea.java
https://igniterealtime.org/issues/browse/SPARK-1597
=> Fix for SPARK-1597

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/LoginSettingDialog.java
=> Add ProxyInfo for connection config

src/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java, src/java/org/jivesoftware/sparkimpl/plugin/phone/PhonePlugin.java, src/plugins/sip/src/java/org/jivesoftware/sparkplugin/ui/call/CallManager.java
Reverted some changed made in SPARK-1455 by removing use of a negative priority value.
=> SPARK-1726

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/LoginSettingDialog.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties
@guusdk  Please review..In my test, this restores sparks previous behavior of allowing self signed certs, etc over tls.
=> SPARK-1739

src/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java, src/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java
Both problems had the same source.
=> SPARK-1735 and SPARK-1749

src/resources/i18n/spark_i18n_it.properties
Now I created a dedicated branch for translation. I shouldn't mess up your work anymore. 
Thank you for your patience ;)
=> Italian translation

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
https://igniterealtime.org/issues/browse/SPARK-1559
=> fix for  SPARK-1559

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
removed not used imports/code, transparent bg, centered close button
=> SPARK-1559 visual fixes

build/rpm/spark.spec
=> SPARK-1769 Add lib for RPM build

build/rpm/spark.spec
=> SPARK-1771 - Update RPM spec file

src/java/org/jivesoftware/sparkimpl/plugin/idle/IdleTime.java, src/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java, src/java/org/jivesoftware/sparkimpl/plugin/idle/linux/LinuxIdleTime.java, src/java/org/jivesoftware/sparkimpl/plugin/idle/mac/MacIdleTime.java, src/java/org/jivesoftware/sparkimpl/plugin/idle/windows/Win32IdleTime.java
reworked the idle plugin a little. this should better detect user input
=> SPARK-1773

src/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java
=> Spark-1777 Presence getting stuck in Away

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/spark/ui/login/GeneralLoginSettingsPanel.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties
added an option to disable tls host name verification
=> Spark-1787 Add option to disable TLS hostname verification

src/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
=> SPARK-1798: Handle exception thrown by eventhandler.

src/java/org/jivesoftware/spark/util/BrowserLauncher.java
Now user can open links which was pointed to Spark forum
=> Added support for open link which pointed to Spark forum when user uses KDE

src/java/org/jivesoftware/spark/PluginManager.java, src/java/org/jivesoftware/spark/util/BrowserLauncher.java
=> Spark -1816

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastDialog.java
https://issues.igniterealtime.org/projects/SPARK/issues/SPARK-1051
=> Fix SPARK-1051

src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastDialog.java
Reverts igniterealtime/Spark#239
=> Revert "Fix SPARK-1051"

src/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
This should get the presences and return system icon to the correct icon.
=> SPARK-1520

src/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
Reverts igniterealtime/Spark#238
=> Revert "SPARK-1520"

src/java/org/jivesoftware/spark/PresenceManager.java
Reverts igniterealtime/Spark#261
=> Revert "SPARK-1026 changing default DND priority to -1"

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/resource/default.properties, src/java/org/jivesoftware/sparkimpl/plugin/manager/Enterprise.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties
- Add a "login anonymously" checkbox to the login dialog
- Support anonymous login using Smack
- Minor format/typo fixes
=> SPARK-1852: Add anonymous SASL login support

src/java/org/jivesoftware/LoginDialog.java, src/java/org/jivesoftware/spark/ui/ContactList.java, src/java/org/jivesoftware/spark/ui/ReconnectPanel.java, src/java/org/jivesoftware/spark/ui/ReconnectPanelIcon.java, src/java/org/jivesoftware/spark/ui/ReconnectPanelSmall.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreference.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferencePanel.java, src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, src/resources/i18n/spark_i18n.properties
This is an attempt to make the re-connection delay configurable, with a 10 sec default..  While doing so, removed the reconnection code from the ReconnectPanel(s) UI, since its now being handled by the reconnection manager.
=> Reconnection delay setting

core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java
=> SPARK-1876: Spark history window should wrap text

core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java
=> SPARK-1635

core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscript.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java
=> SPARK-1875: Spark history search should show context

core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardManager.java
This commit revisits an earlier fix for SPARK-1812. Instead of skipping fixed number of XML nodes,
the parser should skip until at the start of the vCard element that's identified by name/namepace.
Also, file references should be closed, even in case of an error (the try-with-resources construct
will make sure this happens).
Finally, when a file cannot be parsed, that file should be deleted.
=> SPARK-1812: Parse vCards on disk

core/src/main/java/org/jivesoftware/spark/ChatManager.java
I hope I have done good selection of less green colors.
=> SPARK-1912 remove green username colors from chat room

core/pom.xml, core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java
=>  SPARK-1903: Highlight searched keyword in the history search

core/src/main/java/org/jivesoftware/spark/ui/CustomTextEntry.java, core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java, core/src/main/java/org/jivesoftware/spark/ui/StartOfDayEntry.java, core/src/main/java/org/jivesoftware/spark/ui/TimeStampedEntry.java, core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindow.java, core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindowEntry.java
New joined/left and other presence messages still will appear durning conversation, but not informations about who joined/left before we joined the room.
=> SPARK-1909 Green blob of user join/left messages now is on top of the transcript window.

core/src/main/java/org/jivesoftware/spark/component/MessageDialog.java, core/src/main/java/org/jivesoftware/spark/component/TitlePanel.java, core/src/main/java/org/jivesoftware/spark/ui/conferences/ConferenceRoomBrowser.java, core/src/main/java/org/jivesoftware/spark/ui/conferences/DataFormDialog.java, core/src/main/resources/i18n/spark_i18n.properties
Lots of minor tweaks. @wrooot I'll leave it up to you if any of these are JIRA-issue-worthy.
=> Minor tweaks

core/src/main/java/org/jivesoftware/spark/ui/login/CertificateDialog.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateDialogReason.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateModel.java, core/src/main/resources/i18n/spark_i18n.properties
Deleting certificates, additional field with information about validity and fixed bug with not displayable information about expired/not valid yet certificate.
=> SPARK-1945, SPARK-1957, SPARK-1936

core/src/main/java/org/jivesoftware/spark/ui/themes/LookAndFeelManager.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/chat/PresenceChangePlugin.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/emoticons/EmoticonManager.java, core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardManager.java
Various improvements that should make Spark a bit faster. Apart from making unavailable three themes, no functional changes should be introduced by any of these commits.
=> Efficiency

core/src/main/java/org/jivesoftware/spark/PluginManager.java
Should fix the unloading of plugins (and thus, fix the re-installing and updating of plugins). Please note that this PR is completely untested by me - @wrooot - could you do the honors please?
=> SPARK-1888: Plugin management

core/src/main/java/org/jivesoftware/spark/ui/login/CertificateDialog.java, core/src/main/java/org/jivesoftware/spark/ui/login/CertificatesManagerSettingsPanel.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java, core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
SPARK-1953, SPARK-1959, SPARK-1980
=> SPARK-1953, SPARK-1959, SPARK-1980 and some work on blacklist

core/src/main/java/org/jivesoftware/spark/ButtonFactory.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/emoticons/EmoticonManager.java
in case we don't have smile emotion in pack we will select  first image from our package and set up this image as button
=> Added protection in case we dont have smile Emotion

core/src/main/java/org/jivesoftware/spark/util/GraphicUtils.java
Remove usage of sun.awt.shell for getting icon image
=> Spark-2017 Remove usage of sun.awt.shell

core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java
I was intending to reduce number of times when this error happens with this commit but it seems that I cannot reproduce error again after this changes. 
I reworked and simplified a bit moving certificates to/from exceptions. With this change exempted certificates are used as information to set "tick box" in certificate table instead of displaying separate list of certificates. 
That means I only read certificates from TrustStores while ExceptionsStores are used for management. 
I hope it solves problem with random NullPointerException because I can't reproduce it now (but I still don't know what caused it so it might be that still happen, just much less frequently).
=> SPARK-1999 Fix Nullpointer that sometimes happens when user add/remove certificate from exceptions

core/src/main/java/org/jivesoftware/spark/ui/login/CertificatesManagerSettingsPanel.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java
Now sorting of the certificates seems to work fine. This PR is at top of the [#406](https://github.com/igniterealtime/Spark/pull/406) which already awaits for merging.
=> SPARK-1951 Cert sorting

core/src/main/java/org/jivesoftware/LoginDialog.java, core/src/main/resources/i18n/spark_i18n.properties
I hope this will work with suppressing that error (somehow I didn't reproduced it myself)
=> SPARK-2001 Suppress error message, remove unnecessary translations dialogs

core/src/main/java/org/jivesoftware/sparkimpl/certificates/InBandCertificateChainDialog.java
Renamed OK to Accept and renamed CertInfoButton to detailsButton for consistency
=> SPARK-2001 Rename button

core/src/main/java/org/jivesoftware/Spark.java, emoticons/pom.xml
How I tests:
On MAC (I tested only in the mac os )
1 mvn install on git clone
2 ./distribution/target/distribution-base/bin/startup.sh
Then check that emoticon is working
=> enable Emoticons SPARK-2068

core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastDialog.java
https://issues.igniterealtime.org/browse/SPARK-1871
=> Fixing output of nicknames in broadcast history[SPARK-1871]

core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java
I have tested one symbol and couple symbols send and seems working for me with chat room
=> fix for SPARK-2043

distribution/src/installer/spark.install4j
Reverts igniterealtime/Spark#450
=> Revert "INFRA-23, SPARK-1988 update to latest install4j"

core/src/main/java/org/jivesoftware/sparkimpl/preference/PreferencesPanel.java
At times, a plugin that integrates with the preferences panel fails to store its configurations. This has been observed with 'old' plugins, that suffer from class-not-found exceptions. When this occurs, Spark should notify the user, but otherwise ignore the issue.
=> SPARK-2065: Show error when preferences cannot be saved.

core/src/main/java/org/jivesoftware/spark/PluginManager.java
This adds a hardcoded list of plugins (with version number) that are known to cause issues. Plugins on the list are no longer loaded by Spark.
=> SPARK-2065: Prevent known incompatible plugins from being loaded.

core/pom.xml, core/src/main/java/org/jivesoftware/Spark.java
This commit fixes the distribution packaging to include the emoticons. Additionally, the code that verifies if emoticons exist in the user home directory is a bit more error resistant now.
=> SPARK-2068: Restore emoticons

core/src/main/java/org/jivesoftware/sparkimpl/plugin/language/LanguagePlugin.java
Instead of specifically looking for i18n-files in the spark.jar file, just check if they're anywhere on the classpath. This is more likely to yield results (especially when Spark isn't ran from a jar file, but from an IDE). I'd not be surprised if it's moderately faster too, as no ZIP file operations are needed).
=> SPARK-2133: Don't search jar for translations

core/src/main/java/org/jivesoftware/Spark.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/RoarMessageListener.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/RoarProperties.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/displaytype/RoarDisplayType.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/displaytype/RoarPopupHelper.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/displaytype/SystemNotification.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/displaytype/WindowsNotification.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/gui/RoarPanel.java
This intends to fix 'everything' (that I know is an issue).
During testing, I did find some odd behavior, which we might want to improve on. Documented here: https://discourse.igniterealtime.org/t/when-should-roar-notifications-be-displayed/88480
=> Various ROAR fixes

plugins/reversi/src/main/java/org/jivesoftware/game/reversi/ReversiPlugin.java, plugins/tictactoe/src/main/java/tic/tac/toe/TicTacToePlugin.java
This fixes the most obvious bugs in TicTacToe and Reversi
Note that during testing, I found another issue with Reversi: https://issues.igniterealtime.org/browse/SPARK-2139
That problem is not fixed in this PR.
=> Spark-2138: Game fixes

core/src/main/java/org/jivesoftware/spark/Workspace.java, core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java, core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
This ensures that exceptions are logged.
=> SPARK-2155: Explicitly log problems with processing stanzas

core/src/main/java/org/jivesoftware/spark/SessionManager.java, core/src/main/java/org/jivesoftware/spark/Workspace.java, core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java, core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java
This is bound to prevent some issues, although I'm not sure which ones :)
I've not tested this change.
=> SPARK-2156: Prevent comparing JID with String for serverAddress

plugins/fastpath/pom.xml, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/panes/AgentConversation.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/panes/AgentConversations.java
This is bound to prevent some issues, although I'm not sure which ones :)
I've not tested this change.
=> SPARK-2157: Prevent comparing JID with String for FastPath agent

plugins/meet/pom.xml, plugins/meet/readme.md, plugins/meet/src/main/java/de/mxro/process/ProcessListener.java, plugins/meet/src/main/java/de/mxro/process/Spawn.java, plugins/meet/src/main/java/de/mxro/process/XProcess.java, plugins/meet/src/main/java/de/mxro/process/internal/Engine.java, plugins/meet/src/main/java/de/mxro/process/internal/StreamListener.java, plugins/meet/src/main/java/de/mxro/process/internal/StreamReader.java, plugins/meet/src/main/java/org/jitsi/util/OSUtils.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/ChatRoomDecorator.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java, plugins/meet/src/main/plugin-metadata/plugin.xml, pom.xml
Electron version of meet plugin
The plugin should work with Windows, Linux and OSX (macs). I have only tested on Windows.  There is a short delay as the plugin fetches the Electron binary from the Electron GitHub web site and unzips it the first time it runs. Next time it starts will be faster.
=> electron version of meet plugin

core/src/main/java/org/jivesoftware/LoginDialog.java, core/src/main/java/org/jivesoftware/resource/Default.java
Reformat code and remove some white space.
Fix behavior of the login dialog related to handling the default property "HOST_NAME_CHANGE_DISABLED".
Replace some string literals with constants.
=> SPARK-2167 Fix handling the default property "HOST_NAME_CHANGE_DISABLED".

pom.xml
See https://issues.igniterealtime.org/browse/SPARK-2161
See https://issues.igniterealtime.org/browse/SPARK-2166
=> Disable ofmeet spark plugin

core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java
Optimize messages rendering in chat area.
Make it possible to correctly handle network addresses containing spaces when enclosed in quotes.
=> SPARK-2169: Rendering messages in chat area

core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java
Changes according to [SPARK-2172](https://issues.igniterealtime.org/browse/SPARK-2172).
=> SPARK-2172: Disable automatic activation of the new private chat room created when the first message arrived

core/src/main/java/org/jivesoftware/spark/ui/ContactGroup.java, core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
I hope one active forum user will be happy. [SPARK-2143](https://issues.igniterealtime.org/browse/SPARK-2143)
=> SPARK-2143: Fix contacts duplication after reconnect

core/src/main/java/org/jivesoftware/spark/Workspace.java, core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
Issue: [SPARK-2175](https://issues.igniterealtime.org/browse/SPARK-2175)
Bug [description](https://discourse.igniterealtime.org/t/spark-2-9-0-after-reconnecting-some-users-change-their-status-to-red/88485/34?u=r87a)
=> SPARK-2175: Fix "only the first offline message comes" bug.

core/src/main/java/org/jivesoftware/spark/ChatManager.java, core/src/main/java/org/jivesoftware/spark/PresenceManager.java, core/src/main/java/org/jivesoftware/spark/component/RosterTree.java, core/src/main/java/org/jivesoftware/spark/ui/ContactItem.java
[SPARK-1160: Replace deprecated methods](https://issues.igniterealtime.org/browse/SPARK-1160)
=> SPARK-1160: Continue getting rid of deprecated methods

core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java
The code to skip the date validation is using an API method that is intended for a very similar, but different purpose.
The change in this commit replaces it, by allowing for the validation to throw an exception, but only re-throw that exception if Spark is not configured to suppress it.
=> SPARK-2194: Fix certificate expiry configuration

core/src/main/java/org/jivesoftware/sparkimpl/plugin/chat/ChatArgumentsPlugin.java
Discussion: https://github.com/orgs/igniterealtime/teams/spark-developers/discussions/3
Issue: https://igniterealtime.atlassian.net/browse/SPARK-1469
=> SPARK-1469: Fix side effect of code cleanup

core/src/main/java/org/jivesoftware/sparkimpl/plugin/filetransfer/transfer/ui/ReceiveFileTransfer.java
This commit adds numbers to file names (similar to what Windows does) when copying a file that already exists.
=> SPARK-2198: Prevent incoming file transfers to overwrite existing files

plugins/meet/pom.xml, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/ChatRoomDecorator.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java, pom.xml
replace sun.misc.BASE64Decoder with javax.xml.bind.DatatypeConverter
=> Run the electron download in a thread

core/src/main/java/org/jivesoftware/spark/util/StringUtils.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/idle/linux/LinuxIdleTime.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/idle/mac/MacIdleTime.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/idle/windows/Win32IdleTime.java, plugins/apple/src/main/java/com/jivesoftware/spark/plugin/apple/AppleDock.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/Workpane.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/assistants/CoBrowser.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/assistants/RoomInformation.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/panes/ChatQueue.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/panes/InvitationPane.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/panes/UserInvitationPane.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/util/RequestUtils.java, plugins/roar/src/main/java/org/jivesoftware/spark/roar/displaytype/MacNotificationCenter.java
- Fix raw using of parametrized classes
- Remove some deprecated methods usage
- Remove statements with empty body
[SPARK-2204: Code cleanup](https://igniterealtime.atlassian.net/browse/SPARK-2204)
=> SPARK-2204: Code cleanup

core/pom.xml, core/src/main/java/org/jivesoftware/MainWindow.java, core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java, core/src/main/java/org/jivesoftware/spark/filetransfer/preferences/FileTransferPreference.java, core/src/main/java/org/jivesoftware/spark/ui/themes/ThemePanel.java
=> Icon and Error Fix - FlatLaf Update

pom.xml
Reverts igniterealtime/Spark#583
=> Revert "SPARK-2212 Smack update to 4.4.0"

core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
Reverts igniterealtime/Spark#590
=> Revert "IBB file transfer should not be enabled by default"

core/src/main/java/org/jivesoftware/spark/component/tabbedPane/SparkTabbedPane.java, core/src/main/java/org/jivesoftware/spark/ui/themes/LookAndFeelManager.java
=> Gui Update

core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
https://discourse.igniterealtime.org/t/spark-change-default-settings-in-future-releases/
=> set idleTime to 5 minutes

core/src/main/java/org/jivesoftware/gui/LoginUIPanel.form, core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java, core/src/main/java/org/jivesoftware/spark/ChatManager.java, core/src/main/java/org/jivesoftware/spark/decorator/DefaultTabHandler.java, core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java, core/src/main/java/org/jivesoftware/spark/ui/ChatRoom.java
=> Update Scrollable Tabs Unread Logic and Disable Componens on Login Process

core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java, core/src/main/java/org/jivesoftware/spark/component/IconTextField.java, core/src/main/java/org/jivesoftware/spark/component/tabbedPane/SparkTabbedPane.java, core/src/main/java/org/jivesoftware/spark/decorator/DefaultTabHandler.java, core/src/main/java/org/jivesoftware/spark/search/SearchService.java, core/src/main/resources/i18n/spark_i18n.properties
=> Gui Update and Some Fixes

core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java
=> Attempted fix for offline contact taking over focus

core/src/main/java/org/jivesoftware/spark/util/StringUtils.java
Replace Ukrainian Belarusian and Russian letters
https://igniterealtime.atlassian.net/browse/SPARK-2233
=> SPARK-2233 replace other letters

core/pom.xml
https://www.bouncycastle.org/releasenotes.html
=> Update Bouncy Castle to 1.70

core/src/main/java/org/jivesoftware/spark/ui/ContactInfoWindow.java, core/src/main/java/org/jivesoftware/spark/util/ModelUtil.java, core/src/main/resources/i18n/spark_i18n.properties, core/src/main/resources/i18n/spark_i18n_ru_RU.properties, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/internal/FormUtils.java, plugins/fastpath/src/main/resources/i18n/fastpath_i18n.properties
The name of Away time(h,min) is now hardcoded, it would be useful if it changed with the language.
=> SPARK-2249 Add translation for hours, min to Awaytime

core/src/main/java/org/jivesoftware/sparkimpl/settings/local/SettingsManager.java
for https://github.com/igniterealtime/Spark/pull/670/
=> fix for verify that the registry value exists before deleting it

core/src/main/java/org/jivesoftware/sparkimpl/plugin/emoticons/EmoticonManager.java
Replace Emoticons  that have a different md5-hash than its correspondant in install\spark\xtra\emoticons .
These methods are taken from PluginManager.java
=> SPARK-1918 Emoticons packs are not updated after the upgrade

core/src/main/java/org/jivesoftware/spark/ui/themes/ThemePanel.java, core/src/main/java/org/jivesoftware/spark/ui/themes/ThemePreference.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java, core/src/main/resources/i18n/spark_i18n.properties, core/src/main/resources/i18n/spark_i18n_de.properties, core/src/main/resources/i18n/spark_i18n_fi.properties, core/src/main/resources/i18n/spark_i18n_fr.properties, core/src/main/resources/i18n/spark_i18n_it.properties, core/src/main/resources/i18n/spark_i18n_ko.properties, core/src/main/resources/i18n/spark_i18n_ky.properties, core/src/main/resources/i18n/spark_i18n_lt.properties, core/src/main/resources/i18n/spark_i18n_nl.properties, core/src/main/resources/i18n/spark_i18n_pl.properties, core/src/main/resources/i18n/spark_i18n_pt_BR.properties, core/src/main/resources/i18n/spark_i18n_ru_RU.properties, core/src/main/resources/i18n/spark_i18n_tr.properties, core/src/main/resources/i18n/spark_i18n_uk_UA.properties, core/src/main/resources/i18n/spark_i18n_zh_CN.properties, core/src/main/resources/i18n/spark_i18n_zh_TW.properties
Add GUI for this PR - https://github.com/igniterealtime/Spark/pull/475
=> SPARK-2116 Add an option to set how many previous messages should be shown in a chat window

core/src/main/java/org/jivesoftware/spark/PluginManager.java, core/src/main/java/org/jivesoftware/spark/Workspace.java, core/src/main/java/org/jivesoftware/spark/ui/ContactList.java, core/src/main/java/org/jivesoftware/spark/ui/conferences/JoinRoomSwingWorker.java, core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java, core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java, core/src/main/java/org/jivesoftware/spark/util/UIComponentRegistry.java, core/src/main/java/org/jivesoftware/sparkimpl/settings/local/SettingsManager.java
This adds log lines that will help show how long particular bits of the initial startup take.
No functional changes are introduced by this commit.
=> Add debug logging for startup timing

core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
I also think it is advisable to show it if the number of accounts is more than 1
=> SPARK-2282 add "Other Users" button for Login text field

core/src/main/java/org/jivesoftware/spark/ui/conferences/DataFormDialog.java
Now the window opens and the changes are saved.
=> SPARK-2283 Configure room button not working after Smack update

core/src/main/java/org/jivesoftware/spark/ui/ContactInfoWindow.java
If width Spark Main Windows > width 0.9*screenSize we should put a window inside
=> Vcard popup not showing when contact window is maximized

core/src/main/java/org/jivesoftware/spark/ui/themes/LookAndFeelManager.java, core/src/main/java/org/jivesoftware/spark/ui/themes/ThemePanel.java, core/src/main/java/org/jivesoftware/spark/ui/themes/lafs/SparkIntelliJLaf.java
Maybe later we can add a dark Look and Feel, but a lot of icons need to be redrawn.
Now I have added another LaF(FlatLaf IntelliJ), they are very similar, you can see the difference here
https://www.formdev.com/flatlaf/themes/
=> Return select theme and add new flat look and feel

core/src/main/java/org/jivesoftware/LoginDialog.java, core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
In session i see correct Resource, but i think we should save resource in spark.properties
=> SPARK-2182 save resource in propetries

core/src/main/java/org/jivesoftware/spark/ui/ContactGroup.java, core/src/main/java/org/jivesoftware/spark/ui/ContactInfoWindow.java
User can open chat with dummy@dummy.example and also when hovering the cursor, a window with contact information is displayed.
=> SPARK-2285 User can open chat with dummy@dummy.example

core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
This bug is due to the fact that from does not have a LocalPart and the server should not have one.
=> SPARK-2218 broadcast message is not displayed on startup

core/src/main/java/org/jivesoftware/spark/ui/conferences/JoinRoomSwingWorker.java
with this fix adding to the room works.
=> SPARK-2294 UI freezes when accepting a room invite

core/src/main/java/org/jivesoftware/MainWindow.java
It would be useful to show JRE bit of Java
=>  Add Java Bit Information

distribution/src/installer/spark.install4j
1.On the first run, install4j updated the configuration to the latest version.
2.I created a 64bit installer (no JRE) for Windows.
@akrherz I tested these changes locally, works well! I would like to merge my branch, please email me when you update install4j to version 10
=> Update install4j to 10version and add Spark 64bit without JRE SPARK-2276 SPARK-2016

plugins/fileupload/pom.xml, plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java
@deleolajide Do you mind if I make changes to your plugin?
Now when uploading a file on the server interface freezes and I can't do anything. It is also not clear what error occurred.
This fix:
-adds a window with an error
-uploads each file in a separate thread.
=> HttpUploadPlugin 0.4 Fix freeze UI. Upload each file in a separate thread.Add dialog

core/src/main/java/org/jivesoftware/SparkStartupListener.java
To do that, create a class that implements the com.install4j.api.launcher.StartupNotification.Listener interface and register it with com.install4j.api.launcher.StartupNotification.registerStartupListener(listener). Your listener will then be notified when another startup occurs. See the [Javadoc](https://www.ej-technologies.com/resources/install4j/help/javadoc/com/install4j/api/launcher/StartupNotification.html) for more information.
=> SPARK-2121 Bring up roster window when shortcut is opened

plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java
* More descriptive logging
* Remove some logging
* Change some log levels
=> SPARK-2305: Improved logging for HTTP FIle Upload

plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java, plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/SparkFileUploadPlugin.java
-Use EntityJid
-Remove unused code
=> SPARK-2317 HTTP File Upload Plugin button not opening in private chat

plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/ChatRoomDecorator.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPreference.java, plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetResource.java, plugins/meet/src/main/resources/i18n/sparkmeet_i18n.properties
=> Add i18n and improve Preference panel for Pade Meeting

plugins/reversi/src/main/java/org/jivesoftware/game/reversi/ReversiPlugin.java, plugins/tictactoe/src/main/java/tic/tac/toe/TicTacToePlugin.java
If the user is offline, then when calling the getJID method, we will always get an exception because the offline user does not have a Resource.
=> SPARK-2163 TicTacToe Reversi throws exception for offline user

core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java
I think you should not request a list of MUC services every time, once is enough for us.
=> Fix freeze when opponent is typing

core/pom.xml, core/src/main/java/org/jivesoftware/sparkimpl/updater/CheckUpdates.java, plugins/sip/src/main/java/org/jivesoftware/sparkplugin/preferences/SipPreference.java
The new version form XStream fixes various vulnerabilities.
=> SPARK-2324: Upgrade XStream from 1.4.19 to 1.4.20

plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java
Noticed the exception in logs, it looks like it's safe to hide
=> SPARK-2302 plugins/ofmeet: hide the NoSuchFieldException sys_paths

core/src/main/java/org/jivesoftware/LoginDialog.java, core/src/main/java/org/jivesoftware/spark/ui/ContactInfoWindow.java, core/src/main/java/org/jivesoftware/spark/ui/conferences/RoomCreationDialog.java, core/src/main/java/org/jivesoftware/spark/util/ModelUtil.java, core/src/main/java/org/jivesoftware/spark/util/URLFileSystem.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertManager.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/GeneralTrustManager.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkExceptionsTrustManager.java, core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java, core/src/main/java/org/jivesoftware/sparkimpl/profile/AvatarPanel.java, core/src/main/java/org/jivesoftware/sparkimpl/settings/UserSettings.java, core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java, core/src/main/resources/i18n/spark_i18n.properties, core/src/main/resources/i18n/spark_i18n_nl.properties, core/src/main/resources/i18n/spark_i18n_ru_RU.properties, core/src/main/resources/i18n/spark_i18n_zh_CN.properties, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/internal/FormUtils.java, plugins/fastpath/src/main/java/org/jivesoftware/fastpath/internal/WorkgroupManager.java, plugins/fastpath/src/main/resources/i18n/fastpath_i18n.properties, plugins/fastpath/src/main/resources/i18n/fastpath_i18n_es.properties, plugins/fastpath/src/main/resources/i18n/fastpath_i18n_pt_PT.properties, plugins/fastpath/src/main/resources/i18n/fastpath_i18n_ru_RU.properties, plugins/fastpath/src/main/resources/i18n/fastpath_i18n_zh_CN.properties
Minor improvements to improve code quality, remove legacy code and improve readability
=> SPARK-2337 Refactor and cleanup

core/src/main/java/org/jivesoftware/LoginDialog.java, core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java, core/src/main/java/org/jivesoftware/spark/component/InputDialog.java, core/src/main/java/org/jivesoftware/spark/component/PasswordDialog.java, core/src/main/java/org/jivesoftware/spark/ui/RosterDialog.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/InputTextAreaDialog.java, core/src/main/java/org/jivesoftware/sparkimpl/plugin/language/LanguagePlugin.java, plugins/spelling/src/main/java/org/jivesoftware/spellchecker/SpellcheckChatRoomDecorator.java, plugins/spelling/src/main/java/org/jivesoftware/spellchecker/SpellcheckerPreferenceDialog.java
Yet another PR with minor changes and cleanup that I made while investigating code base.
=> SPARK-2337 Refacroring, cleanup and reformat

core/src/main/java/org/jivesoftware/MainWindow.java
https://igniterealtime.atlassian.net/browse/SPARK-2350
=> SPARK-2350: MainWindow: avoid NPE when running from IDE and attempt to restart

core/src/main/java/org/jivesoftware/sparkimpl/plugin/language/LanguagePlugin.java
https://igniterealtime.atlassian.net/browse/SPARK-2351
=> SPARK-2351: Always show Language in menu item for non en locales

core/src/documentation/spark.doap, core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java
The list of XEPs may be not complete and some XEPs are possibly not fully implemented but this is a good start.
=> SPARK-2122: spark.doap: add implemented XEPs
