igniterealtime/Spark

src/java/org/jivesoftware/sparkimpl/preference/notifications/NotificationsUI.java

https://igniterealtime.org/issues/browse/SPARK-1645

Notifications settings shouldn't be blank when updates are disabled

---

src/java/org/jivesoftware/spark/filetransfer/ChatRoomTransferDecorator.java
src/java/org/jivesoftware/spark/filetransfer/SparkTransferManager.java

The file selection dialog fails to pass the selected file to Spark
under some conditions (which include native implementation of the OS
and filesystem). This commit fixes this behavior.

SPARK-1650: Fix file select dialog (for transfer)

---

build/build.xml

commented out since it wasn't working with Bamboo remote agent.  Same temp fix appears to have been used with the openfire dmg builder. Unable to test.

SPARK-1091 mac dmg builder

---

src/plugins/apple/build.xml

The missing symbols are included in the oracle jdk in rt.jar. By added the compiler argument -DXignore.symbol.file to the apple plugin build, everything compiles.
info on the compiler switch
https://github.com/mcourteaux/MultiTouch-Gestures-Java
https://stackoverflow.com/questions/4065401/using-internal-sun-classes-with-javac
Another option is to include AppleJavaExtensions.jar lib. It looks like Apple hasn't updated AppleJavaExtensions.jar in a few years, with the last version being 1.6 in 2011
https://developer.apple.com/legacy/library/samplecode/AppleJavaExtensions/Introduction/Intro.html

Apple installer improvements

---

build/build.xml

This should now display "Spark" instead of "Startup"

SPARK-1677-Shows app name as Startup instead of Spark on Mac OS X

---

build/build.xml
src/java/org/jivesoftware/Spark.java
src/java/org/jivesoftware/spark/PluginManager.java
src/java/org/jivesoftware/sparkimpl/plugin/emoticons/EmoticonManager.java

Reverting changes made from previous PR, but updating build.xml to add the appdir system variable that was missing from the mac launcher.

Spark-1701, Spark-1696, Spark-1620 

---

src/java/org/jivesoftware/spark/ChatManager.java
src/java/org/jivesoftware/spark/decorator/DefaultTabHandler.java
src/java/org/jivesoftware/spark/ui/ChatContainer.java
src/java/org/jivesoftware/spark/ui/SparkTabHandler.java
src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java

Reverts igniterealtime/Spark#98
Looks like Fastpath is again in the way. It is using SparkTabHandler and these changes cause Bamboo not to build:
[javac] /opt/j2ee/domains/igniterealtime.org/bamboo/atlassian-bamboo-5.9.7/data/xml-data/build-dir/SPARK-INSTALL4J-JOB1/src/plugins/fastpath/src/java/org/jivesoftware/fastpath/FastpathTabHandler.java:36: error: FastpathTabHandler is not abstract and does not override abstract method isTabBroadcastHandled(SparkTab,Component,boolean,boolean) in SparkTabHandler
03-Mar-2016 12:53:37 	    [javac] public class FastpathTabHandler extends SparkTabHandler {

Revert "Correct Broadcast message . Now broadcastPlugin handle broadcast mess…"

---

build/build.xml

Mac build fails with only removing java bin file

Reverting build.xml changes to include java for mac in repository SPARK-1674

---

src/java/org/jivesoftware/sparkimpl/plugin/scratchpad/PrivateNotes.java

Reverts igniterealtime/Spark#104
Can't open Notes at all after applying this patch. I think my notes were empty before that. No error is generated in the logs.

Revert "Fix for Spark-1714"

---

src/java/org/jivesoftware/sparkimpl/plugin/filetransfer/transfer/ui/ReceiveFileTransfer.java

Changed "//" to File.separator for support both Windows and unix

Move to File separator Jira-1699

---

src/plugins/sip/src/java/net/java/sipmack/sip/NetworkAddressManager.java

Looks like this should be `==` when returning 0.

Duplicate conditional in NetworkAddressManager.java

---

src/plugins/roar/src/java/org/jivesoftware/spark/roar/RoarProperties.java

This commit fixes the problem for which SPARK-1613 was re-opened (the actual problem does not relate to SPARK-1613 though).

SMACK4: Prevent NPE in Roar plugin.

---

build/rpm/spark.spec

The rpm spec file needed ant 1.8.1 to be installed in /opt. I'd rather it assumed that an ant is in the $PATH somewhere. Unless someone thinks it needs a feature from ant 1.8.1??

Remove path to old ant version and assume it is in the PATH

---

build/rpm/spark.spec

Build says : 
[rpm] RPM build errors:
[rpm] error: Not a directory: /var/atlassian/bamboo-home/xml-data/build-dir/SPARK-NIGHTLYRPM-JOB1/work/rpm/BUILDROOT/Spark-2.7.7.841-1.x86_64/usr/bin/spark
Because it was a %dir. Changed to a file with 755 permission and owned by root.

Remove %dir from spark binary in RPM spec

---

src/plugins/fastpath/src/java/org/jivesoftware/fastpath/FastpathPlugin.java
src/plugins/fastpath/src/java/org/jivesoftware/fastpath/WorkgroupInitializer.java

The Fastpath/workgroup classes should be loaded in the ProviderManager.
This does not happen by default in Smack 4.1 (see SMACK-729). This commit
adds a bit of code that works around that issue.

SPARK-1745: Workgroup provider should be loaded

---

src/java/org/jivesoftware/LoginDialog.java
src/java/org/jivesoftware/spark/util/SwingWorker.java

This commit restored the automatic reconnection that's attempted
by Spark, when an XMPP connection unexpectedly fails. The commit
makes use of a construct offered by Smack (which was changed from
Smack 3 to 4).

SPARK-1750: Spark should reconnect by default.

---

src/java/org/jivesoftware/spark/SessionManager.java

When Spark reconnects successfully, the previous presence state of
the local user should be restored.

SPARK-1750: Restore presence after reconnect

---

src/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

1-on-1 message displaying is tricky. When in a regular chat, Spark
should listen to messages sent by any resource, associated to any
of the JIDs of the peer. In context of a MUC private message however,
the filter MUST be applied to the full jid (which will be:
roomname@servicename/nickname).

SPARK-1776: Display all 1-on-1 messages

---

src/java/org/jivesoftware/spark/filetransfer/SparkTransferManager.java

The file transfer manager should, if enabled, always get initialized.
The old code depended on a authentication to succeed. However, if that
occurred before the file transfer manager was invoked, initialization
would never occur.

SPARK-1752: File transfer manager should always be initialized

---

src/java/org/jivesoftware/spark/ui/conferences/GroupChatParticipantList.java
src/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java

This commit attempts to prevent that the occupants list in a MUC
screen has a near-zero width.

SPARK-1735: MUC occupants list should have width

---

src/java/org/jivesoftware/spark/ChatManager.java
src/java/org/jivesoftware/spark/ui/TranscriptWindow.java

When an event listener throws an exception, it should not prevent other
listeners from being executed, nor should the exception propagate further
up the stack (which would stop processing).

SPARK-1798: Gracefully handle exceptions from event listeners.

---

src/java/org/jivesoftware/sparkimpl/profile/VCardManager.java

I read there might be a bug in the parser cause it to not always advance .  a workaround appears to be to add another next().  This resolved the issue for me in my testing.

Spark-1812 Vcard fields not updating automatically when viewing a profile

---

src/java/org/jivesoftware/LoginDialog.java
src/java/org/jivesoftware/MainWindow.java
src/java/org/jivesoftware/resource/Default.java
src/java/org/jivesoftware/resource/default.properties
src/java/org/jivesoftware/spark/ui/status/StatusBar.java
src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/viewer/PluginViewer.java
src/java/org/jivesoftware/sparkimpl/profile/VCardEditor.java

This PR will allow the following 8 new settings in the **default.properties** file:
- **HIDE_LOGIN_AS_INVISIBLE**
- **DISABLE_PREFERENCES_MENU_ITEM**
- **MAINT_FILESPEC**
- **DISABLE_PRESENCE_STATUS_BAR**
- **DISABLE_STATUS_IN_SYSTRAY**
- **DISABLE_BROADCAST_MENU_ITEM**
- **DISABLE_AVATAR_TAB**
- **DISABLE_PLUGINS_MENU_ITEM**
These allow the administrator increased control over the Spark client installation. Comments in the **default.properties** file describe each setting.

SPARK-1822 - Added new settings to disable certain GUI menu items

---

src/java/org/jivesoftware/resource/Default.java
src/java/org/jivesoftware/resource/default.properties
src/java/org/jivesoftware/spark/ui/ContactList.java
src/java/org/jivesoftware/spark/ui/status/StatusBar.java
src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/chat/ContactListAssistantPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
src/java/org/jivesoftware/sparkimpl/profile/VCardEditor.java

The following additional settings in the _default.properties_ file are now available:
- HIDE_LOGIN_AS_INVISIBLE
- DISABLE_PREFERENCES_MENU_ITEM
- MAINT_FILESPEC
- DISABLE_PRESENCE_STATUS_CHANGE
- DISABLE_BROADCAST_MENU_ITEM
- DISABLE_AVATAR_TAB
- DISABLE_PLUGINS_MENU_ITEM

SPARK-1822 - Add additional default properties to control GUI settings

---

src/java/org/jivesoftware/spark/ui/ContactList.java

This PR will resolve the issue of displaying an empty "Unfiled" group in Spark.

SPARK-1758 - Do not show UNFILED group if it's empty

---

src/java/org/jivesoftware/resource/default.properties
src/java/org/jivesoftware/spark/filetransfer/ChatRoomTransferDecorator.java
src/java/org/jivesoftware/spark/filetransfer/SparkTransferManager.java
src/java/org/jivesoftware/spark/ui/ContactList.java
src/java/org/jivesoftware/spark/ui/status/StatusBar.java
src/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/chat/ContactListAssistantPlugin.java
src/java/org/jivesoftware/sparkimpl/plugin/scratchpad/ScratchPadPlugin.java
src/java/org/jivesoftware/sparkimpl/profile/VCardManager.java

When Broadcasting is disabled in Client Control, Spark only removes Broadcast option from in the main menu and in context menu of a group. But users are still able to select a group of users and send a broadcast to them.

SPARK-1827 - Shouldn't allow broadcast to selected users when it is disabled in Client Control

---

src/java/org/jivesoftware/spark/ui/status/StatusBar.java

This prevents a non-existing avatar from being processed.

SPARK-1853: Fix NPE when not adding an avatar.

---

src/java/org/jivesoftware/MainWindow.java
src/java/org/jivesoftware/spark/ui/ContactList.java

When logging off, the contact list is first hidden, but pops up again as part of the
connection-close event handling. This causes "an error has occurred, would you like to
reconnect" type of message to be displayed. This should be prevented.

SPARK-1855: Don't show contact list after logoff.

---

src/java/org/jivesoftware/LoginDialog.java
src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferencePanel.java
src/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java

SPARK-1858 and SPARK-1850.  This should clear saved password when the option is deselected, and hide/disable the save password option when using sso.

SPARK-1850

---

src/java/org/jivesoftware/spark/ui/conferences/JoinRoomSwingWorker.java

When joining a MUC room, allow a user to change its nickname, when the initial nickname is already in use.

SPARK-1860: Resolve MUC nickname conflict.

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java

when joining a multi user chat room, the recent history of that room can be sent to the client.
A bug in Spark caused these mesages to be processed as history (which is good), but also as
regular/new messages (which is wrong). As a result of this, the messages could be presented in
the wrong order on screen (SPARK-1757), as the original date of the message was not processed.
Also, all event listeners got triggered, causing other components to act as if a new message
was received. This causes issues like SPARK-1649 (unwanted notifications). Finally, the history
was being saved in the local history - which can introduce some duplication there (when a room
is rejoined frequently).

SPARK-1757 & SPARK-1649: Don't process MUC history as regular messages.

---

core/pom.xml
core/src/main/java/org/jivesoftware/sparkimpl/profile/AvatarPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardEditor.java

Implemented a image resizing and cropping functionality to resize and crop large images.
Vcards doesn't support large sized images and requires square images. This fix meet both of these requirements.

Fix for SPARK-1872: Should resize large photo when applying as an avatar

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscript.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java

Fixes SPARK-1875:
Added one line before and after searched message.
Added yellow highlighter over searched message.

SPARK-1875: Spark history search should show context

---

core/pom.xml

The artifacts smack-resolver-javax and smack-sasl-javax are transitive
dependencies of smack-java7. That is all we need to depend on.

Don't declare transitive Smack dependencies

---

core/src/main/java/org/jivesoftware/spark/Workspace.java
core/src/main/java/org/jivesoftware/spark/ui/ChatArea.java
core/src/main/java/org/jivesoftware/spark/ui/ChatInputEditor.java
core/src/main/java/org/jivesoftware/spark/ui/ChatRoom.java
core/src/main/java/org/jivesoftware/spark/ui/ChatRoomTransferHandler.java
core/src/main/java/org/jivesoftware/spark/ui/CustomTextEntry.java
core/src/main/java/org/jivesoftware/spark/ui/HorizontalLineEntry.java
core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java
core/src/main/java/org/jivesoftware/spark/ui/StartOfDayEntry.java
core/src/main/java/org/jivesoftware/spark/ui/TimeStampedEntry.java
core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindow.java
core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindowEntry.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
core/src/main/resources/default.properties

This commit started off as a fix for SPARK-1757, but ended up being somewhat of a rewrite of the
code that displays chat messages in the UI (the 'chat transcript window').
The original problem defines that chat messages are sometimes displayed out of order. The direct cause
of this is unknown (I suspect threading/timing issues). To work around the issue, this commit now
adds the capability to recompose the entire transcript window from memory.
A drawback of this is that a(nother) copy of the chat is now kept in memory (the 'entries' list that
is now added to TranscriptWindow). This might make Spark use more memory.
I've opted for a rewrite, as in the course of applying fixes to the existing code, I repreatedly got
lost in the jungle of reuse of styling, particularly. This commit adds new …

Transcript Window should be recomposable.

---

core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/PresenceManager.java
core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindow.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/chat/ContactListAssistantPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/manager/Enterprise.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscriptPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java
core/src/main/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java

Currently Client Control plugin's setting "History Settings" not just hides the history settings, but also disables the history in Spark. Which might not be desired. One might need to have history, but hide settings, so users won't be able to disable it from a GUI. This change will implement two separate history features in Client Control - "History Settings" and "History Transcripts". Now an admin can select to enable/disable the history controls as well as enable/disable the logging of the history into transcript files. **NOTE: Updated version 2.1.2 of the Client Control plug-in and minimum of Spark version 2.9.0 is required for proper functionality.**

SPARK-1915 -- Implement separate History settings in Client Control

---

.editorconfig

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
Note that this file defines very basic settings:
- line ending (unix-style)
- last line ends with a newline
- character set (UTF-8)
- indent uses 4 spaces

Adds an EditorConfig file.

---

core/src/main/java/org/jivesoftware/AccountCreationWizard.java
core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/spark/ui/login/GeneralLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/LoginSettingDialog.java
core/src/main/java/org/jivesoftware/spark/ui/login/PkiLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/ProxyLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/SecurityLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/SsoLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/util/DummySSLSocketFactory.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
core/src/main/resources/i18n/spark_i18n.properties

This commit adds a new 'security' tab to the advanced login settings. Here, security-related
settings are made available.
Also, this commit makes slight modifications to the other tabs, by making the components be
oriented more to the top-left corner (instead of being centered - which looks pretty ugly).

SPARK-1972: New 'security' login settings panel.

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/spark/component/MessageDialog.java
core/src/main/resources/i18n/spark_i18n.properties

This commit:
- reworks the login method to remove some redundant code;
- applies the MessageDialog-provided error dialog generator to the login method;
- refactored the MessageDialog error dialog generator (to allow for toggling of the large stacktrace pane).
In all, this should improve the error messages during login. The same technique could be re-used elsewhere.

SPARK-1976: Better error messages

---

core/src/main/java/org/jivesoftware/spark/component/MessageDialog.java

This ensures that the error dialog is centered, in relation to it's parent. Also, when expanding
the details (which changes the size of the dialog), the dialog is repositioned again (to remain
centered).

SPARK-1976: Make sure error dialog is centered.

---

core/src/main/java/org/jivesoftware/sparkimpl/preference/PreferenceDialog.java

The recent fix for SPARK-945 already stored the preference dialog size and position, which fixed most of this bug. When that was implemented, a rogue invocation of .pack() was placed after the stored settings were applied. This resized the component again.

SPARK-1956: Preference dialog should remember its size.

---

pom.xml

This PR is to address SPARK-1987 by disabling the auto build of meet plugin. Not sure how the plugin inflates the installer as it uses a standard plugin pom file and includes Java classes from Spark Core. The change is to eliminate it from the issue.

Disable meet plugin by default.

---

distribution/src/installer/spark.install4j

The Spark install4j installer script is hard-coded to use JxBrowser version 6.12 and is unable to use the dependency version info from maven pom file. This PR upgrades it to use 6.14 which is required for Spark Meet plugin.
This should resolve SPARK-1987

SPARK-1987 Update install4j to jx-browser ver 6.14

---

pom.xml

Now that the JxBrowser runtime file size issue is resolved, I am re-enabling meet plugin to be included by default with Spark

Re-enabling the meet plugin

---

core/src/main/java/org/jivesoftware/spark/ui/login/CertificateDialog.java
core/src/main/java/org/jivesoftware/spark/ui/login/MutualAuthenticationSettingsPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertManager.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateModel.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/IdentityController.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java
core/src/main/resources/i18n/spark_i18n.properties

Refreshing certificate table works. Blacklist is now used for adding status to the Certificate Model, not as separate List in table. Also now button for checking revocation in certificate dialog works.

SPARK-1995, SPARK-1996, SPARK-1997 and lack of resources in one text.

---

core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/ui/login/CertificatesManagerSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/GeneralLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/LoginSettingDialog.java
core/src/main/java/org/jivesoftware/spark/ui/login/ProxyLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/SecurityLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/SsoLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
core/src/main/resources/default.properties
core/src/main/resources/i18n/spark_i18n.properties

At first I was intending to add default settings only to Certificate Manager but as UseDefault button wasn't working for other tabs so I fixed them too. I added default settings to Default class and default.proporties and used it in tabs.

SPARK-2000 Default Settings and lacking resource for mutual.auth

---

core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java

I probably introduced this bug with adding JRE certificates, but it is not related to random NullPointerExceptions. The problem which it generate is that not all certificates from JRE are displayed and that cause further problems at moving certificates to/from exceptions list.

SPARK-2006 Don't use common name as alias if alias already exist.

---

core/src/main/java/org/jivesoftware/sparkimpl/certificates/CertificateController.java

When you tried to remove certificate it was removed only from exemptedCacertsStore but it wasn't added to the distrusted entries. In effect certificate was displayed still but now as trusted JRE certificate.

SPARK-2008 Fix for exempted cacerts certificates removal

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java

Upon receiving messages to be displayed in a chat room UI, don't explicity check if the
sender has voice (the server will have done this). This commit replaces the check with
a check to verify that the sender is a participant in the room (and I'm not even sure if
that's warranted).

SPARK-2029: Don't check for voice

---

core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java

This is a quick and dirty implementation that can (and perhaps should) be improved upon.
It adds basic support, but does not work with nested styles.

SPARK-2030: Add basic Message Styling support

---

core/src/main/java/org/jivesoftware/spark/ui/login/CertificatesManagerSettingsPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java

Use of PKIXRevocationChecker instead of custom code for downloading CRLs. This way checker's options are better used (and soft fail policy can be set with just CRL's). Also some comments were improved.

SPARK-2045 Make better use of PKIXRevocationChecker

---

plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/UploadRequest.java

[Http file upload plugin] in Openfire was updated from 1.1.2 to 1.1.3 in 2/19.
The problem is that it changed the response format in compliance to XEP-format ([commit link]):
```java
slotElement.addElement( "put" ).setText( url.toExternalForm() );
slotElement.addElement( "get" ).setText( url.toExternalForm() );
```
to
```java
if ( isPre030Style )
{
slotElement.addElement( "put" ).setText( url.toExternalForm() );
slotElement.addElement( "get" ).setText( url.toExternalForm() );
}
else
{
slotElement.addElement( "put" ).addAttribute( "url", url.toExternalForm() );
slotElement.addElement( "get" ).addAttribute( "url", url.toExternalForm() );
}
```
So this causes parsing error in the fileupload plugin in Spark.
This PR will conflict with previous 1.1.2 version of Openfire plugin, so one should …

Fileupload plugin: change uploadrequest parsing function

---

plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java

Fileupload plugin can upload file only once, and the next upload fails because of this bug.
`Putmethod.getURI()` seems to omit port number if the port of `Protocol` matches with that of the instance.
So I assumed that if `URI.getPort()` returns -1, the protocol need not be changed.

Fileupload plugin: fix invalid port bug

---

core/src/main/java/org/jivesoftware/AccountCreationWizard.java
core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkSSLContextCreator.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkSSLSocketFactory.java

It's more a cleanup PR as it doesn't bring any functional changes. I am removing here some dead code, as class SparkSSLContext inherit SSLContext without reason because SSLContext is created by it's static method.

Removing some dead code.

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/jabber/JabberVersion.java

After an upgrade of Smack, Spark stopped responding correctly to requests for its software version (per XEP-0092). This commit configures Smack with the desired software version response data, which restores functionality.

SPARK-1811: Restore XEP-0092 functionality.

---

core/src/main/java/org/jivesoftware/sparkimpl/search/users/SearchForm.java

When a search for users results in no hits, a popup used to be shown, but is no longer. This commit restores the functionality.

SPARK-2107: restore popup when user search results are empty.

---

core/src/main/java/org/jivesoftware/spark/PluginManager.java
core/src/main/java/org/jivesoftware/spark/util/StringUtils.java
core/src/test/java/org/jivesoftware/spark/util/JavaVersionTest.java

Without this, plugins that define a minimum Java version of 9 or lower fail to load on Java 10 or higher.

SPARK-2114: Fix Java version string comparison.

---

plugins/fastpath/pom.xml
plugins/fastpath/src/main/java/org/jivesoftware/fastpath/WorkgroupInitializer.java

A API change in Smack went unnoticed, and caused the FastPath plugin to not load correctly. This commit fixes that, and increases the version number of the plugin.

SPARK-2092: Fix Fastpath plugin

---

core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindow.java

Without this, an error occurs when trying to add messages to a window that has no history.

SPARK-2085: No-history transcript window bugfix.

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java

Configurable by adding/changing an integer value for 'currentHistoryMaxSize' in spark.settings. I've not added a visual config thingy yet.

SPARK-2116: Make maximum value for 'current' transcript size configurable

---

core/pom.xml
plugins/systemtray/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

core/pom.xml
core/src/main/java/org/jivesoftware/spark/PluginManager.java
core/src/main/java/org/jivesoftware/spark/component/browser/EmbeddedBrowserViewer.java
distribution/src/installer/spark.install4j
plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java
pom.xml

This re-introduces the (likely broken) LoboBrowser, in favor of JxBrowser (for which we can't obtain a license). Using Lobobrowser is far from ideal (we'd ideally go with something more modern), but with moving out JxBrowser, we at least remove a release blocker.

SPARK-2132: No more JxBrowser

---

core/src/assembly/installation-directory.xml

The 'sounds' directory (and some other files) used to live outside of the spark.jar file in Spark 2.8.3. This commit mostly restores this.
I'm leaving out the emoticons, as I think that has been tackled in SPARK-2068.

SPARK-1979: Restore distribution archive directory for 'sounds'

---

core/src/main/java/org/jivesoftware/spark/ui/RosterDialog.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardEditor.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardManager.java

Smack has deprecated parts of the VCard API (primarily the 'load' and 'save' methods). As Spark still used this API at some points, some data doesn't get refereshed / loaded properly. By switching to the new API, these problems disappear.

SPARK-2110: Stop using deprecated VCard API

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/spark/ui/login/LoginSettingDialog.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/SettingsManager.java
core/src/main/resources/i18n/spark_i18n.properties
core/src/main/resources/i18n/spark_i18n_nl.properties

The way the 'advanced settings' dialog of the login screen works, causes it to save its configuration to file whenever 'an event' happens.
When saving the configuration, the state of the various UI elements (checkboxes, radiobuttons, etc) is used to update the configuration file.
Eligble events happen more often than expected, for example, when the dialog is disposed (which can occur much later after when it was closed). By that time, the settings of the UI elements can be outdated. This causes an issue where settings are unexpectedly 'reverted'.
This commit works around this problem by only allowing the settings to be updated while the screen is visible.

OF-2079: Ensure settings are properly saved upon login

---

core/src/main/java/org/jivesoftware/spark/ChatManager.java
core/src/main/java/org/jivesoftware/spark/UserManager.java
core/src/main/java/org/jivesoftware/spark/ui/VCardPanel.java
core/src/main/java/org/jivesoftware/spark/ui/VCardViewer.java
core/src/main/java/org/jivesoftware/spark/uri/UriManager.java

The implementation that unescapes JIDs unintentionally removes the '@' character (separating node- and domain-part). This commit restores that character.

SPARK-2110: Fix nicknames & add missing '@' in result of unescaping JIDs

---

core/src/main/java/org/jivesoftware/LoginDialog.java

We ideally enable Stream Management (see SPARK-2140), but for that, the reconnection logic in Spark probably needs work. I'm disabling it for now, until we have had a proper look.

Disable Smacks support for Stream Management (for now)

---

core/src/main/java/org/jivesoftware/spark/component/RosterTree.java
core/src/main/java/org/jivesoftware/spark/ui/ContactList.java

This commit restores functionality that already existed, but was ... disabled?
When a user is not in any group on the contact list, it is now displayed in a psuedo-group, called 'unfiled' (this is similar to the 'offline contacts' psuedo group).

SPARK-2141: Contacts should always be shown, even if they're not in a group

---

core/pom.xml

Bouncy Castle 1.65 instead of 1.57: https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
CVEs: https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

SPARK-2146: Bouncy Castle 1.65 instead of 1.57

---

core/src/main/java/org/jivesoftware/spark/ui/conferences/BookmarksUI.java

The bookmark name should contain the name of the room. It's preferable to show the name of the room in the listing of bookmarked rooms, as opposed to the room ID.

SPARK-2012: Use bookmark name when listing rooms

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

When a mesasge including an error is received, display an error message to the end-user, so that they know something went wrong.

SPARK-1895: Show errors in chat transcript.

---

core/pom.xml

The check is currenty optional and placed
inside the profile 'owasp-check'.
One can directly invoke the plugin via
`mvn org.owasp:dependency-check-maven:check`
An attempt at resolving SPARK-2113.

Add OWASP dependency check to build

---

plugins/apple/pom.xml
plugins/battleships/pom.xml
plugins/fastpath/pom.xml
plugins/fileupload/pom.xml
plugins/flashing/pom.xml
plugins/growl/pom.xml
plugins/jingle/pom.xml
plugins/meet/pom.xml
plugins/reversi/pom.xml
plugins/roar/pom.xml
plugins/sip/pom.xml
plugins/spelling/pom.xml
plugins/systemtray/pom.xml
plugins/tictactoe/pom.xml
plugins/transferguard/pom.xml
plugins/translator/pom.xml

Since the last release, major changes were applied to the project. To reflect this, I've increased the version number of all of the plugins.
Not all plugins might have had functional changes, but given that the project structure has changed a lot, some kind of increase (that will allow us to tell plugins before and after this release apart) could be helpful.

Increase version number of all plugins

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

When opening a chat window, the previously exchanged messages are displayed. In this history, your own nickname should be used, instead of your own JID.

SPARK-2148: Fix displaying of own nickname in history

---

core/src/main/java/org/jivesoftware/sparkimpl/preference/notifications/NotificationPlugin.java

Notifications (when enabled) should online occur when a user that was previously online goes offline, or the other way around.

SPARK-2149: Prevent notification from popping up on every presence change

---

core/src/main/java/org/jivesoftware/spark/plugin/PluginDependency.java

This likely fixes a problem that has never occurred, as I do not think we have plugins that specify dependencies. Still...

SPARK-2158: fix comparison of plugin dependency version numbers.

---

core/src/main/java/org/jivesoftware/spark/ui/conferences/GroupChatParticipantList.java

This is bound to prevent some issues in the group chat screen, although I've not seen such problems yet, or tested this change.

SPARK-2157: Prevent comparing JID with String for groupchat comparison

---

core/src/main/java/org/jivesoftware/spark/Workspace.java

Nicknames aren't necessarily components of a Jid (they are in context of MUC, but they're pretty much free form text on the roster). By attempting to use the Jid implementation to parse nicknames, exceptions occur. In this instance, such an exception prevents an offline message being displayed if it is sent by someone that is on the recipients roster using in nickname that contains a space.

SPARK-2154: Do not parse nicknames using Jid implementation

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/MainWindow.java
core/src/main/java/org/jivesoftware/Spark.java
core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/PresenceManager.java
core/src/main/java/org/jivesoftware/spark/filetransfer/SparkTransferManager.java
core/src/main/java/org/jivesoftware/spark/search/SearchService.java
core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
core/src/main/java/org/jivesoftware/spark/ui/RosterDialog.java
core/src/main/java/org/jivesoftware/spark/ui/TranscriptWindow.java
core/src/main/java/org/jivesoftware/spark/ui/login/ProxyLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/spark/ui/status/StatusBar.java
core/src/main/java/org/jivesoftware/spark/ui/themes/MainThemePanel.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/chat/ContactListAssistantPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/scratchpad/ScratchPadPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscriptPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/viewer/PluginViewer.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/viewer/SparkPlugUI.java
core/src/main/java/org/jivesoftware/sparkimpl/preference/chat/ChatPreferencePanel.java
core/src/main/java/org/jivesoftware/sparkimpl/preference/notifications/NotificationsUI.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardEditor.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardManager.java
core/src/main/java/org/jivesoftware/sparkimpl/search/users/UserSearchResults.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferencePanel.java
core/src/main/resources/default.properties

1. Add missed string constants (static final fields) for default properties to Default class.
2. Replace string literals with constants from Default class.
3. Clean up grammar and typos, refactor some unobvious property names and remove trailing white space.

Add more consistency to default properties usage

---

core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java

It was a minor algorithmic error.

SPARK-2170: Fix converting emote expressions to icons

---

core/src/main/java/org/jivesoftware/spark/SparkManager.java
core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/history/ConversationHistoryPlugin.java

Use unescaped JID to prevent creating files with backslashes in the name.

SPARK-2162: Fix history issues for contacts with spaces in usernames

---

core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java
core/src/main/java/org/jivesoftware/spark/ui/ChatRoom.java
core/src/main/java/org/jivesoftware/spark/ui/conferences/GroupChatParticipantList.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java

To address private rooms in a group chat, you need to use full JID instead of bare JID.
[See section 7.5 of XEP-0045: Multi-User Chat](https://xmpp.org/extensions/xep-0045.html#privatemessage)

SPARK-2153: Fix private messaging in group chat.

---

core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java
core/src/main/java/org/jivesoftware/spark/ui/ChatRoom.java
core/src/main/java/org/jivesoftware/spark/ui/ContactGroup.java
core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
core/src/main/java/org/jivesoftware/spark/ui/conferences/ConferenceUtils.java
core/src/main/java/org/jivesoftware/spark/ui/conferences/GroupChatParticipantList.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/GroupChatRoom.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscriptPlugin.java
plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/Workpane.java
plugins/fastpath/src/main/java/org/jivesoftware/fastpath/workspace/invite/WorkgroupInvitationDialog.java
plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java
plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/SparkFileUploadPlugin.java
plugins/roar/src/main/java/org/jivesoftware/spark/roar/RoarMessageListener.java

Contact list behavior corrected according to items no. 2, 3 and 5 of [ilyaHlevnoy feedback](https://discourse.igniterealtime.org/t/spark-2-9-0-after-reconnecting-some-users-change-their-status-to-red/88485/12?u=r87a).
No change of contact's status to offline in the dialog box when the user lost the connection (item no. 1 of feedback) seems to be another issue, that shoud be reported.
Item no. 4 of feedback - I could not understand what it was about :). 
Also fixed one-on-one chats broken during [SPARK-2153](https://issues.igniterealtime.org/browse/SPARK-2153) fix.

SPARK-2143: Fix behavior of contact list during reconnection

---

core/src/main/java/org/jivesoftware/spark/decorator/DefaultTabHandler.java
core/src/main/java/org/jivesoftware/spark/ui/SparkTabHandler.java
core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

[SPARK-2143](https://issues.igniterealtime.org/browse/SPARK-2143): Added reconnection event handling to one-on-one chat room. 
[SPARK-2174](https://issues.igniterealtime.org/browse/SPARK-2174): Changing tab icons of chat rooms to "unavailable" when disconnected.

SPARK-2143, SPARK-2174

---

core/src/main/java/org/jivesoftware/spark/ChatManager.java
core/src/main/java/org/jivesoftware/spark/Workspace.java
core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java

This prevents new tab creation for chat room that has already been opened. [SPARK-2175](https://issues.igniterealtime.org/browse/SPARK-2175)

SPARK-2175: Fix offline message handling after a reconnect

---

core/src/main/java/org/jivesoftware/spark/SessionManager.java
core/src/main/java/org/jivesoftware/spark/ui/status/StatusBar.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/idle/UserIdlePlugin.java

- Prevent automatic status change to away/offline during reconnection
- Disable manual status change during reconnection
- Add offline status text to the status panel
Issue ticket: [SPARK-2177](https://issues.igniterealtime.org/browse/SPARK-2177)

SPARK-2177: Fix own presence state during and after a reconnection

---

core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkExceptionsTrustManager.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java

In a previous commit, the regular trust manager got some updates. This commit adds similar updates to the 'exception' trust manager.

Apply learnings from SPARK-2185 and SPARK-2186 to 'exception' trust manager

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/Spark.java
core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/manager/Enterprise.java

This commit augments the blacklist of plugins with the response to a query to the clientControl plugin for Openfire.
This functionality is added to the clientControl plugin in what will probably be release 2.1.6. See https://github.com/igniterealtime/openfire-clientControl-plugin/pull/18

SPARK-2005: Query ClientControl for additions to plugin blacklist

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/filetransfer/transfer/ui/ReceiveFileTransfer.java

Sometimes, Spark cannot open a file. In that case, it should open the folder that contains the file, so that the end user can at least try through OS-specific measures.

SPARK-2199: Show folder if file cannot be opened

---

core/pom.xml

Dependabot replaced the regular version of XStream with one that's 'java7' classified. This introduces a ClassNotFound exception.
This causes various XML file processing (such as done during update checks) to fail.
This commit replaces the XStream dependency with the regular variant, which resolves the issue.

Replace XStream with more compatible version

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/filetransfer/transfer/ui/ReceiveFileTransfer.java

When a file is received, it could be renamed (see SPARK-2198). The name that's displayed in the confirmation text needs to be modified accordingly.

SPARK-2207: Display correct name for received file

---

plugins/fileupload/pom.xml
plugins/fileupload/src/main/java/org/jivesoftware/spark/plugin/fileupload/ChatRoomDecorator.java

This PR replaces the deprecated sun.misc.BASE64Decoder with javax.xml.bind.DatatypeConverter
It was causing a NPE in the fileupload plugin

update the base64 decoder

---

pom.xml

There is currently no way to turn off Meet from the Openfire console due to the spaces in the name. Therefore, so that users do not face network load, you need to turn off this plugin.

Disable meet plugin

---

pom.xml

Hi, now Openfire can control Meet plugin https://github.com/igniterealtime/openfire-clientControl-plugin/pull/25
Therefore, I think we need to enable this plugin.

Enable meet plugin

---

core/src/main/java/org/jivesoftware/spark/PluginManager.java

In the logs, I see that the name of the plugin is stick together with the word "as".

name of the plugin is stick together with the word "as"

---

core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java

When a message had more than one line break, like this:
```
a
b
c
```
the following problem used to happen:
now that problem has been fixed, it will appear like this, as it should:
explanation of what I did, if necessary:
first, I changed **new StringTokenizer(text, "\n", false);** to **new StringTokenizer(text, "\n", true);** for it to return the delimiters as tokens, and it caused a problem of doubling each line-breaks.
For that reason, I refactored to add a new line only when finished the insertion on the lines of the block.

Fix ignoring of line breaks

---

core/src/main/java/org/jivesoftware/spark/ui/CustomTextEntry.java
core/src/main/java/org/jivesoftware/spark/ui/HorizontalLineEntry.java
core/src/main/java/org/jivesoftware/spark/ui/MessageEntry.java
core/src/main/java/org/jivesoftware/spark/ui/StartOfDayEntry.java

This fixes an issue where repeatedly setting the caret position when populating a chat room with historic messages freezes the UI completely.

SPARK-2234: Fix 'freeze' when joining a new chat

---

core/src/main/java/org/jivesoftware/spark/ui/ChatArea.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/HistoryTranscript.java

The size of the text should change in the message history and in the writing area

SPARK-2063 SPARK-2120 The size of the text should change in the message history and in the writing area

---

core/src/main/java/org/jivesoftware/sparkimpl/profile/ext/VCardUpdateExtension.java

Fixes
java.lang.IllegalStateException: Illegal to call getName() when event type is CHARACTERS. Valid states are START_ELEMENT, END_ELEMENT
at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.getName(XMLStreamReaderImpl.java:938)
at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getQName(StaxXmlPullParser.java:123)
at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getName(StaxXmlPullParser.java:117)
at org.jivesoftware.sparkimpl.profile.ext.VCardUpdateExtension$Provider.parse(VCardUpdateExtension.java:75)
at org.jivesoftware.sparkimpl.profile.ext.VCardUpdateExtension$Provider.parse(VCardUpdateExtension.java:62)
at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:83 …

[core] Fix VCardUpdateExtension.Provider

---

core/pom.xml

I see that this library has not been updated for a long time. New versions contain fixes and improvements. I think we should update to the latest version.
https://github.com/coobird/thumbnailator/wiki/Changes
A quick test shows that there are no exceptions or errors in the IDE, the avatars are loaded.

Update Thumbnailator to 0.4.15

---

core/src/main/java/org/jivesoftware/sparkimpl/preference/sounds/SoundPreference.java

The XStream library that takes care of deserializing XML data to a class instance needs to be configured to allow certain classes to be instantiated.

SPARK-2241: Allow SoundPreferences class to be deserialized

---

core/src/main/java/org/jivesoftware/resource/Res.java
core/src/main/java/org/jivesoftware/resource/UTF8Control.java
plugins/fastpath/src/main/java/org/jivesoftware/fastpath/FpRes.java
plugins/flashing/src/main/java/org/jivesoftware/spark/plugin/flashing/FlashingResources.java
plugins/reversi/src/main/java/org/jivesoftware/game/reversi/ReversiRes.java
plugins/roar/src/main/java/org/jivesoftware/spark/roar/RoarResources.java
plugins/spelling/src/main/java/org/jivesoftware/spellchecker/SpellcheckerResource.java
plugins/tictactoe/src/main/java/tic/tac/toe/TTTRes.java
plugins/transferguard/src/main/java/org/jivesoftware/spark/plugins/transfersettings/TGuardRes.java

stackoverflow suggest this way to fix utf-8 encoding.
It seems to work and now in java 8, 11, 15 the text is displayed fine.
I wonder if this might be a solution?
https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle

SPARK-2128 SPARK-2160 Fix lang for java 8-17

---

core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java

I think it will be correct to create a new "Download" folder in the root folder if it is not there or if the folder is called in another language in linux.

SPARK-2252

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/ui/login/GeneralLoginSettingsPanel.java
core/src/main/resources/default.properties

There are three problems with SPARK-2182:
1) If ClientControl is not installed on the Openfire server then the HOSTNAME_AS_RESOURCE_FEATURE and VERSION_AS_RESOURCE_FEATURE values ​​are always "true"! To avoid this, you need to compare these values ​​that they are not equal to each other.
2) There are 4 parameters, it's confusing, there should be two. Either HOSTNAME_AS_RESOURCE and VERSION_AS_RESOURCE or USE_HOSTNAME_AS_RESOURCE and USE_VERSION_AS_RESOURCE.
3) Resource name after reconnect is reset to "Spark". The resource must not be hard-coded. you need to use "get" to get the name of the resource.
After applying this PR, I see that by default my resource name is "Spark" and if I choose "Version as resource" or "Hostname as resource" then it works. =)

SPARK-2182 Switches to using hostname as resource after a re-login

---

core/src/main/java/org/jivesoftware/spark/ui/themes/ThemePanel.java

I think there should be no empty spaces between interface elements.

Change appearance layout

---

core/src/main/java/org/jivesoftware/MainWindow.java

This removes an unneeded lock object, replacing it with a traditional synchronized keyword.
No functional changes should be introduced by this change.

Refactor thread-safety on MainWindow.getInstance()

---

core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/spark/ChatManager.java
core/src/main/java/org/jivesoftware/spark/ui/conferences/JoinRoomSwingWorker.java

Swing event handling code runs on a special thread known as the event dispatch thread. Most code that invokes Swing methods also runs on this thread. This is necessary because most Swing object methods are not "thread safe": invoking them from multiple threads risks thread interference or memory consistency errors. Some Swing component methods are labelled "thread safe" in the API specification; these can be safely invoked from any thread. All other Swing component methods must be invoked from the event dispatch thread. Programs that ignore this rule may function correctly most of the time, but are subject to unpredictable errors that are difficult to reproduce.
It's useful to think of the code running on the event dispatch thread as a series of short tasks. Most tasks are invocations of …

SPARK-2257: Make execution on Event Dispatch Thread more explicit

---

core/src/main/java/org/jivesoftware/spark/ui/conferences/ConferenceRoomBrowser.java

Instead of sorting alphabetically, the sort order of the 'occupant count' column should be numeric.

SPARK-2265: Fix sorting MUC rooms by occupant

---

core/src/main/java/org/jivesoftware/spark/util/URLFileSystem.java

These methods are not used and use reflection.
This raises a warning for Java 11-15. Due to the strong encapsulation introduced starting from jdk 16 some non-public classes, methods and fields of the java.* package are no longer available via reflection.

SPARK-2272 SPARK-2270 Remove unused methods in URLFileSystem.class

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

[Alex Matthews](https://discourse.igniterealtime.org/u/qoole/summary) provided a fix for this problem. I tested it on two different devices and now the message comes to the correct tab and not to everyone
https://discourse.igniterealtime.org/t/muc-private-messages-all-other-tabs-being-taken-over-when-signed-in-to-multiple-sessions/91623?u=ilyahlevnoy

SPARK-2269 Incorrect handling of carbons

---

core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkTrustManager.java
core/src/main/resources/default.properties

1.OCSP should be disabled by default.
2.We have to handle the exception "Certificate does not specify OCSP responder"
I'm confused, maybe I should drop OCSP and remove it. How do you think?

SPARK-2235 Stop requiring OCSP

---

core/src/main/resources/default.properties

Since [SPARK-2209](https://igniterealtime.atlassian.net/browse/SPARK-2209) is fixed, I think IBB should be enabled by default because it transfers files better.

Revert SPARK-2216

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/manager/Enterprise.java

Some administrators may want to manage IBB settings via the ClientControl Openfire plugin.

SPARK-2277 Add control over IBB file transfer via ClientControl

---

core/src/main/java/org/jivesoftware/spark/ui/themes/lafs/SparkLightLaf.java

Renamed Flat*Laf.install() methods to Flat*Laf.setup() to avoid confusion
with UIManager.installLookAndFeel(LookAndFeelInfo info). The old
Flat*Laf.install() methods are still there, but marked as deprecated. They
will be removed in a future version.
https://github.com/JFormDesigner/FlatLaf/releases/tag/1.2

SPARK-2214 Replace depricated method "install"

---

core/pom.xml
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/spark/ui/themes/LookAndFeelManager.java

In the latest versions of FlatLaf [CLICK](https://github.com/JFormDesigner/FlatLaf/pull/442), it's possible to add a clear and show password button to the field. I think we should use this.

SPARK-2279 SPARK-2280 Add clear button for Login text field and eye button to show password

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/jabber/JabberVersion.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/jabber/VersionViewer.java

After upgrading from Smack 4.3.X to Smack 4.4.X, the "View client version" menu does not work. 
Now menu is working
And also if User is offline(NPE is thrown) i think we should catch this exception and show Information message.

SPARK-2281 Fix menu "View client version" and add notification window

---

core/src/main/java/org/jivesoftware/sparkimpl/plugin/alerts/BroadcastPlugin.java

Now the panel doesn't get wide and the line break works. Also, if there is a lot of text, a scroll appears.

SPARK-2288 Fix BroadcastPane

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java

If the contact is not in our list then we should show it's LocalPart and not ResourcePart.

SPARK-2250 Incorrect display of the name if the contact is not in the list of users.

---

core/src/main/java/org/jivesoftware/sparkimpl/certificates/SparkExceptionsTrustManager.java

I think with a self-signed certificate, an exception should be thrown in order to get into the catch block.

SPARK-2266 Always accepts self-signed certificates

---

core/src/main/java/org/jivesoftware/MainWindow.java

I think we need to add additional buttons to the log window so that users can quickly find the folder with logs or copy the log with errors.

SPARK-2292 Improve the log window

---

core/src/main/java/org/jivesoftware/spark/ui/rooms/ChatRoomImpl.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscriptPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java

1.We must use JID(fullname) for save and load history
2.When loading history we must use for name:
a)LocalPart for contacts that are not in user list.
b)ResourcePart for private messages in MUC
3.Jid.asUrlEncodedString() path is not displayed correctly

SPARK-2250 SPARK-2223 Incorrect Display name and load MUC History

---

core/src/main/java/org/jivesoftware/AccountCreationWizard.java

The new version of Smack 4.4.X requires an allow flag to be specified otherwise an exception is thrown

SPARK-2295 Unable to create an account through Spark

---

core/src/main/java/org/jivesoftware/AccountCreationWizard.java
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java

I think if the user has chosen an insecure connection, then we should allow him to change his password in Spark.

SPARK-2115 SPARK-2295 Allow change password for unsecurity connection

---

distribution/src/installer/spark.install4j

Spark 64bit should uninstall past versions of Spark 32bit and vice versa
https://stackoverflow.com/questions/57557144/install4j-64-bit-setup-doesnt-uninstall-previous-32-bit-version

SPARK-2276 SPARK-2016 Install4j 64-bit Setup doesn't uninstall previous 32-bit Version

---

distribution/src/installer/spark.install4j

SPARK-1795:
Starting with install4j we can create MSI installers. Many administrators will be happy =)
https://www.ej-technologies.com/products/install4j/whatsnew8.html
SPARK-2296:
The installer supports many languages. We must show the language if it is in Spark

SPARK-1795 SPARK-2296 MSI installer for Windows and add localizations in install4j installer

---

distribution/src/installer/spark.install4j

macOS single bundle is deprecated. This media file type is deprecated because of signature requirements in modern macOS versions. Use the single bundle archive instead and configure a setup application in the media wizard that is run the first time the user starts the application.
[install4j Help - Media files](https://www.ej-technologies.com/resources/install4j/help/doc/concepts/mediaFiles.html)
https://igniterealtime.atlassian.net/browse/SPARK-2299

SPARK-2299 replace depricated installer for MacOS

---

plugins/fileupload/src/main/plugin-metadata/plugin.xml
plugins/meet/src/main/plugin-metadata/plugin.xml

@deleolajide Thank you very much for these plugins.
I see that they can work on different platforms.
I think we should enable them on Linux and MacOS.
Tested with Linux Ubuntu

Linux and MacOs can useFileUploadPlugin and SparkMeetPlugin

---

core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/ui/themes/LookAndFeelManager.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java
core/src/main/resources/default.properties

When testing MacOS, it does not use FlatLaf. Many elements are displayed only in FlatLaf (text when entering a log / password / domain), we should use only it.
The developer of FlatLaf tells us that we are using a different theme.
https://github.com/JFormDesigner/FlatLaf/issues/617

SPARK-2310 MacOS doesn't use Look and Feal FlatLaf

---

core/src/main/java/org/jivesoftware/spark/ui/ChatContainer.java

If MUC private chat is open you cannot open MUC
For example: I open MUC test@conference.openfire.local then and there I click on the admin user and open a private chat in MUC (he has jid = test@conference.openfire.local/admin). After that, I close the MUC chat and if I try to open the MUC again, Spark will show me a tab with a private chat until I close all the private chats in this MUC.

 SPARK-2316 unable to open MUC while MUC private chat is open

---

plugins/apple/src/main/plugin-metadata/plugin.xml
plugins/battleships/src/main/plugin-metadata/plugin.xml
plugins/fastpath/src/main/plugin-metadata/plugin.xml
plugins/fileupload/src/main/plugin-metadata/plugin.xml
plugins/flashing/src/main/plugin-metadata/plugin.xml
plugins/growl/src/main/plugin-metadata/plugin.xml
plugins/jingle/src/main/plugin-metadata/plugin.xml
plugins/meet/src/main/plugin-metadata/plugin.xml
plugins/otr/src/main/plugin-metadata/plugin.xml
plugins/reversi/src/main/plugin-metadata/plugin.xml
plugins/sip/src/main/plugin-metadata/plugin.xml
plugins/spelling/src/main/plugin-metadata/plugin.xml
plugins/systemtray/src/main/plugin-metadata/plugin.xml
plugins/tictactoe/src/main/plugin-metadata/plugin.xml
plugins/transferguard/src/main/plugin-metadata/plugin.xml
plugins/translator/src/main/plugin-metadata/plugin.xml

Spark supports Java 8 and above.
Starting with Spark 3.0.0, translations are no longer distorted(with java 9 and above), we need to build on this version

SPARK-2322 Raise the minimum requirements for plugins

---

core/src/main/java/org/jivesoftware/spark/ui/conferences/ConferenceUtils.java
core/src/main/java/org/jivesoftware/spark/ui/conferences/JoinRoomSwingWorker.java

By announcing an avatar in the presence stanza that is used to join a MUC room, other occupants can see the avatar of the user that's joining (if their client support showing avatars).

SPARK-2334: Announce avatar when joining a room

---

core/src/docbook/installation-debian.sgml

Instead of the old Sun Java use the default-jre package. Add a link to GitHub Releases page from which to get the deb package. Add wget command to download.
Use apt to install the package: it will also install dependencies (none for now but for a future). Add Russian translation.
The .deb file can be improved and just declare own dependency to the JRE.

docbook/installation-debian.sgml: improve commands and ru translation

---

core/pom.xml
pom.xml

Build failed with the message: 
maven-resources-plugin:3.3.1 (default-resources) on project spark-core: filtering Spark/core/src/main/resources/jniwrap.dll to Spark/core/target/classes/jniwrap.dll failed with MalformedInputException: Input length = 1
This happens because the maven-resources-plugin tries to filter (e.g. replace variables) all files including the binary DLLs.
The only file that uses the filtering is the `spark.properties` so I added only it to the filtering.
Additionally I upgraded dependencies to a more stable versions.

Fix maven build

---

core/src/main/java/org/jivesoftware/AccountCreationWizard.java
core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/spark/ui/login/SecurityLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java

The code uses a term "Old SSL" for Direct TLS connections on port 5223.
This is supported by [XEP-0368](https://xmpp.org/extensions/xep-0368.html) and may be not necessary for old clients.
To make the code follow same terminology as XEP I renamed the LocalPreferences.isSSL() to isDirectTls(). The property name in properties file internally remains same.
Additionally extract the similar code to configure TLS in the Login and AccountCreationWizard.

SPARK-2338 Refactor: rename the confusing "Old SSL" to "Direct TLS"

---

core/src/main/java/org/jivesoftware/sparkimpl/settings/local/LocalPreferences.java

From the [Modern XMPP Client design guidelines](https://docs.modernxmpp.org/client/design/#contact-list):
> The client MUST display offline contacts by default
All existing settings will be keep because stored in properties. The change applied only for new profiles.

SPARK-2339 Make showOfflineUsers true by default

---

core/src/main/java/org/jivesoftware/spark/util/GraphicUtils.java

Avoid allocation `new ImageIcon(img)` when the image can be used as is without scaling.
The scaleImageIcon is called on each contact popup so if we can optimize it a little bit that would be good.
The resulted image is not modified anywhere after so it's safe to return the original image.

SPARK-2340 refactoring: GraphicUtils.scaleImageIcon(): scale only if needed

---

core/src/main/java/org/jivesoftware/spark/SoundManager.java
core/src/main/java/org/jivesoftware/spark/UserManager.java
core/src/main/java/org/jivesoftware/spark/component/AutoCompleteDocument.java
core/src/main/java/org/jivesoftware/spark/ui/ContactList.java
core/src/main/java/org/jivesoftware/spark/ui/login/GSSAPIConfiguration.java
core/src/main/java/org/jivesoftware/sparkimpl/certificates/OIDTranslator.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/history/ConversationHistoryPlugin.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/transcripts/ChatTranscripts.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/viewer/PluginViewer.java
core/src/main/java/org/jivesoftware/sparkimpl/profile/VCardManager.java
core/src/main/java/org/jivesoftware/sparkimpl/settings/JiveInfo.java

Fixed some problems that were highlighted by IntelliJ.
Removed almost all usages of `map.containsKey(key)` and the `map.get(key)` to improve performance and make the lookup only once.
Cleaned code for the PluginViewer while investigated an issue of missing plugins explained here https://discourse.igniterealtime.org/t/spark-plugins-repositiry-is-empty/94464
The diff looks huge but just use the IntelliJ to see changes that can hide spaces and you'll find that most of changes are simple and straightforward

SPARK-2337 refactoring, cleanup and minor perf improvement

---

distribution/src/installer/spark.install4j

https://igniterealtime.atlassian.net/browse/SPARK-2346
The launcher has a the std out/err log redirection that doesn’t work and when I starting the Spark I see the exception: 
java.io.FileNotFoundException: log file directory '/opt/Spark/logs' doesn't exist.
at com.exe4j.runtime.LauncherEngine.checkRedirectionFile(LauncherEngine.java:196)
at com.exe4j.runtime.LauncherEngine.doRedirection(LauncherEngine.java:172)
at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:59)
at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:69)
at install4j.org.jivesoftware.launcher.Startup.main(Unknown Source)

SPARK-2346 make default-jre or any other JRE for Linux Deb

---

core/src/main/java/org/jivesoftware/LoginDialog.java
core/src/main/java/org/jivesoftware/MainWindow.java
core/src/main/java/org/jivesoftware/gui/LoginUIPanel.java
core/src/main/java/org/jivesoftware/resource/Default.java
core/src/main/java/org/jivesoftware/spark/ui/login/GeneralLoginSettingsPanel.java
core/src/main/java/org/jivesoftware/sparkimpl/plugin/systray/SysTrayPlugin.java
core/src/main/resources/default.properties

Use APP_NAME from spark.properties instead of APPLICATION_NAME from default.properties.
This is confusing to have two similar properties with the same value in two separate configs.

Use APP_NAME from spark.properties

---

core/src/documentation/spark.doap

A Description Of A Project file contains metadata used to describe the project. It is used by tools like the software inventory on the XMPP.org website to render a listing.

SPARK-2122: Add DOAP file for project

---

plugins/meet/pom.xml
plugins/meet/readme.md
plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/ChatRoomDecorator.java
plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/QueryRequest.java
plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPlugin.java
plugins/meet/src/main/java/org/jivesoftware/spark/plugin/ofmeet/SparkMeetPreference.java
plugins/meet/src/main/resources/i18n/sparkmeet_i18n.properties

This change implements XEP: 0483 HTTP Online Meetings with a fall-back to the meeting URL configured in Spark preferences. There is support for auto-discovering and creating meeting URLs for  jitsi, galene and ohun.
It also updates Electron to latest version.

Implement XEP: 0483 HTTP Online Meetings

---

core/src/main/resources/i18n/spark_i18n.properties
core/src/main/resources/i18n/spark_i18n_cs.properties
core/src/main/resources/i18n/spark_i18n_de.properties
core/src/main/resources/i18n/spark_i18n_es.properties
core/src/main/resources/i18n/spark_i18n_fi.properties
core/src/main/resources/i18n/spark_i18n_fr.properties
core/src/main/resources/i18n/spark_i18n_it.properties
core/src/main/resources/i18n/spark_i18n_ja.properties
core/src/main/resources/i18n/spark_i18n_ko.properties
core/src/main/resources/i18n/spark_i18n_ky.properties
core/src/main/resources/i18n/spark_i18n_lt.properties
core/src/main/resources/i18n/spark_i18n_nl.properties
core/src/main/resources/i18n/spark_i18n_pl.properties
core/src/main/resources/i18n/spark_i18n_pt_BR.properties
core/src/main/resources/i18n/spark_i18n_ru_RU.properties
core/src/main/resources/i18n/spark_i18n_sv.properties
core/src/main/resources/i18n/spark_i18n_tr.properties
core/src/main/resources/i18n/spark_i18n_uk_UA.properties
core/src/main/resources/i18n/spark_i18n_zh_CN.properties
core/src/main/resources/i18n/spark_i18n_zh_TW.properties

The preamble is not really useful and it definitely must not be copied to translations. Instead I added a link to the Transifex so that users will see the proper way to submit translations.
This also reduced size of i18n from 976K down to 956K i.e. saved 20kb.

i18n: remove preamble from files
